apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-claim
spec:
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
  volumeMode: {{ .Values.persistentVolumeClaim.volumeMode }}
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessMode }}